export default {
  multipass: true,
  plugins: [
    "cleanupAttrs",
    "cleanupEnableBackground",
    "cleanupIDs",
    "collapseGroups",
    "convertColors",
    "convertPathData",
    "convertShapeToPath",
    "convertStyleToAttrs",
    "convertTransform",
    "mergePaths",
    "minifyStyles",
    "moveElemsAttrsToGroup",
    "moveGroupAttrsToElems",
    "removeComments",
    "removeDesc",
    "removeDimensions",
    "removeDoctype",
    "removeEditorsNSData",
    "removeElementsByAttr",
    "removeEmptyAttrs",
    "removeEmptyContainers",
    "removeEmptyText",
    "removeHiddenElems",
    "removeMetadata",
    "removeNonInheritableGroupAttrs",
    "removeRasterImages",
    "removeStyleElement",
    "removeTitle",
    "removeUnknownsAndDefaults",
    "removeUnusedNS",
    "removeUselessDefs",
    "removeUselessStrokeAndFill",
    "removeViewBox",
    "removeXMLProcInst",
    "sortAttrs",
  ],
  js2svg: {
    pretty: true,
    indent: "  ",
  },
}
